version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      LOCAL: "true"
      PORT: 8080
      DATABASE_URL: postgresql://postgres:donotshare@postgresql/grabjobs?sslmode=disable
      REDIS_URL: redis
    depends_on:
      - postgres
      - redis


  postgres:
    container_name: postgresql
    image: mdillon/postgis:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: donotshare
      POSTGRES_DB: grabjobs

  redis:
    image: redis:alpine



